### ISSUE TITLE
Ocean Monument generation issues

### ISSUE THREAD

**Issue by esotericist** [McJtyMods/LostCities#53]
Ocean Monuments appear to be spawning in fairly arbitrary biomes; I am right now looking at an ocean monument which spawned under a Meadow/Bog area:

![Unlikely Monument](https://media.discordapp.net/attachments/360995219321126935/373731033352503296/2017-10-28_00.11.18.png?width=1063&height=552)

In my current survival world, I have ocean monuments far underneath deserts (so the water isn't visible), and in other unlikely places.

Vanilla monuments should only be spawning in Deep Ocean (with some admittedly complex rules).

This is MC 1.12.2, forge 2501, Lost Cities 1.0.1, BiomesOPlenty-1.12.2-7.0.1.2298. Plus other mods.

**Comment by esotericist** [comment]
Source of problem found and described in #52

**Comment by Kataiser9** [comment]
Same issue here.

I'm not a pro coder, but based on what Esotericist said (monument generation screws up if allowedBiomeFactors is non-empty), I poked around in the code a bit and noticed that having non-empty allowedBiomeFactors results in a LostWorldFilteredBiomeProvider being used. This provider's "areBiomesViable" method always returns true, and so (AFAICT) the ocean monument's biome check will also always be true, thereby spawning monuments regardless of biome. (Sorry if I'm off base here, but I _think_ this is the issue.)

I am unsure if this mod is still supported, but I hope it is, 'cause it's cool stuff.

**Comment by McJty** [comment]
Probably fixed by @esotericist
